In [45]:
import pandas as pd

In [46]:
df = pd.read_csv('../data/raw/03-bank_marketing.csv', sep=';')

In [47]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [48]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='str')

In [49]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [50]:
df['pdays'] = df['pdays'].replace(999, -1)

In [51]:
cols = ['job','marital','education','default','housing','loan']
for col in cols:
    df[col] = df[col].replace('unknown', 'other')

In [52]:
df = df.drop(columns=['duration']) ##se borra porque impacta directamente en la variable objetivo, una llamada larga se puede asociar a que si acepta el deposito, pero esto no es posible porque contiene informacion posterior a lo que se requiere predecir

In [53]:
df['y'] = df['y'].map({'yes':1,'no':0})

In [54]:
df['contacted_before'] = (df['previous'] > 0).astype(int)

In [55]:
df['campaign_intensity'] = df['campaign'] / (df['previous'] + 1)
df['campaign_intensity'] = df['campaign_intensity'].clip(0, 10)

In [56]:
df['age_group'] = pd.cut(
    df['age'],
    bins=[18,30,45,60,100],
    labels=['young','adult','mid','senior']
)

In [57]:
df['has_loan_or_housing'] = (
    (df['loan'] == 'yes') | (df['housing'] == 'yes')
).astype(int)

In [58]:
df = pd.get_dummies(df, drop_first=True).astype(int)

In [59]:
df

,age,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,...,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success,age_group_adult,age_group_mid,age_group_senior
0,56,1,-1,0,1,93,-36,4,5191,0,...,0,1,0,0,0,1,0,0,1,0
1,57,1,-1,0,1,93,-36,4,5191,0,...,0,1,0,0,0,1,0,0,1,0
2,37,1,-1,0,1,93,-36,4,5191,0,...,0,1,0,0,0,1,0,1,0,0
3,40,1,-1,0,1,93,-36,4,5191,0,...,0,1,0,0,0,1,0,1,0,0
4,56,1,-1,0,1,93,-36,4,5191,0,...,0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,1,-1,0,-1,94,-50,1,4963,1,...,0,0,0,0,0,1,0,0,0,1
41184,46,1,-1,0,-1,94,-50,1,4963,0,...,0,0,0,0,0,1,0,0,1,0
41185,56,2,-1,0,-1,94,-50,1,4963,0,...,0,0,0,0,0,1,0,0,1,0
41186,44,1,-1,0,-1,94,-50,1,4963,1,...,0,0,0,0,0,1,0,1,0,0
41187,74,3,-1,1,-1,94,-50,1,4963,0,...,0,0,0,0,0,0,0,0,0,1